name: Deploy React App with PM2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Deploy and start app on server
        uses: appleboy/ssh-action@master
        with:
          host: 34.46.49.87
          username: ibukun_o
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2

            cd /home/ibukun_o/auth-backend
            git pull origin main
            npm install --legacy-peer-deps

            pm2 restart auth-backend || pm2 start index.js --name auth-backend